### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tuvqlu** [Laith98Dev/LevelSystem#10]
Hello, it says could not check compatibility between FormAPI, I deleted formapi, and it still says that.

Fatal Error
![F69D4543-7258-4CD2-ADB1-08A283171828](https://user-images.githubusercontent.com/98550458/154865025-8133c993-f701-4b55-8116-97d8f09be45b.jpeg)

Help, thanks!

**Comment by Laith98Dev** [comment]
You need to wait a new update for libFormAPI or u can get fixed version from my discord server

**Comment by Tuvqlu** [comment]
Is your discord server PKPVP? Which channel?

**Comment by SigitGamers** [comment]
U can change api use pocketmine\Player; on FormAPI to use pocketmine\player\Player;
