### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by Tuvqlu** [Laith98Dev/LevelSystem#11]
Hey it still crashed with form api 1.4.0

**Comment by Laith98Dev** [comment]
error?

**Comment by Tuvqlu** [comment]
If I do /ls it crashes says can’t find FormAPI even with FormAPI

**Comment by Laith98Dev** [comment]
Ok thx i will fix it

**Comment by Tuvqlu** [comment]
Ty bro, could you also make it so we can have different colors for different levels Tysm.

also another bug, I edited the level up message and it doesn’t change

Also a command reward for leveling up would be pog

Ty laith!
